// ============================================================
// Cantaia — Tracking Code Service
//
// Extraction of `SUB-` tracking codes from incoming supplier
// response emails (Level 0b of the classification pipeline and
// the receive-quote route).
//
// AUDIT 08/2026 — the legacy `PR-` chain (generateTrackingCode /
// extractTrackingCode / validateAndResolvePriceRequest + hardcoded
// HMAC secret) was removed: it resolved against the dead
// `price_requests` table and had ZERO callers outside the barrel.
// Live tracking codes are the `SUB-XXXX-slug-YYYYYY` format
// generated by /api/submissions/[id]/send-price-requests.
// ============================================================

/**
 * Extract SUB-xxx tracking codes from text.
 *
 * Canonical format (see send-price-requests):
 *   SUB-{4 uppercase hex of submission id}-{lowercase slug}-{6..32 uppercase hex}
 *   (suffix was 6 hex / 24 bits historically; new codes carry 16 hex / 64 bits —
 *   the {6,32} range keeps both generations extractable)
 *
 * Matching is CASE-INSENSITIVE: a supplier who retypes
 * "sub-a3f8-facade-x9k2p1" by hand must still match. Every match is
 * normalized back to the canonical casing (prefix/short-id/suffix upper,
 * slug lower) so `.eq("tracking_code", code)` lookups keep working.
 */
export function extractSubmissionTrackingCodes(text: string): string[] {
  if (!text) return [];

  const regex = /SUB-[A-Z0-9]{4}-[A-Z0-9-]+-[A-Z0-9]{6,32}/gi;
  const matches = text.match(regex);
  if (!matches) return [];

  const normalized = matches.map((raw) => {
    const parts = raw.split("-");
    // parts[0] = "SUB" | parts[1] = 4-char short id | parts[2..n-2] = slug | last = 6-char suffix
    const shortId = (parts[1] || "").toUpperCase();
    const suffix = (parts[parts.length - 1] || "").toUpperCase();
    const slug = parts.slice(2, -1).join("-").toLowerCase();
    return `SUB-${shortId}-${slug}-${suffix}`;
  });

  return [...new Set(normalized)];
}
